// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghqpanbtfcfrmmzxolgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdocXBhbmJ0ZmNmcm1tenhvbGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNDQyNjcsImV4cCI6MjA3MDcyMDI2N30.igehM8-Yp7DDbwzOeedcFHBJeC6fa6k7mRxqQviGmKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});